name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - run: cargo build --release
    - run: gcc -Wall -Wextra -Werror -Iinclude -Ltarget/release -o example/main example/main.c -lrcf
    - run: example/main
