name: release
on: workflow_dispatch
jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        include:
        - target: x86_64-unknown-linux-gnu
          os: ubuntu-22.04
        - target: aarch64-unknown-linux-gnu
          os: ubuntu-22.04
        - target: x86_64-apple-darwin
          os: macos-latest
        - target: aarch64-apple-darwin
          os: macos-latest
        - target: x86_64-pc-windows-msvc
          os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: ankane/rust-release@v1
      with:
        target: ${{ matrix.target }}
        files: |
          example
      id: rust-release
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.rust-release.outputs.artifact-name }}
        path: ${{ steps.rust-release.outputs.artifact-path }}
